#pragma once

#include "CoreMinimal.h"
#include "MeshDescription.h"
#include "Track/ApexTrackSceneData.h"
#include "UObject/ObjectPtr.h"

class AActor;
class FReferenceCollector;
class ULevel;
class UMaterialInterface;
class UStaticMesh;
class UStaticMeshComponent;
class UTexture;
class UWorld;

APEXSIM_API DECLARE_LOG_CATEGORY_EXTERN(LogApexTrack, Log, All);

/**
 * The four parent materials every track instantiates. They are cooked
 * assets under `/Game/Materials/Track`, generated by the editor's
 * `ApexMaterialBake` commandlet (the track import runs it when they are
 * missing), so a cooked level and a track built at runtime share them.
 */
struct FApexTrackParents
{
	/** `M_ApexTrackBase`: every road, band, marking and generated stand-in. */
	TObjectPtr<UMaterialInterface> Base;
	/** `M_ApexEmissive`: start lights, lamps and screens. */
	TObjectPtr<UMaterialInterface> Emissive;
	/** `M_ApexBrand`: a texture on a matte surface, for boards and flags. */
	TObjectPtr<UMaterialInterface> Brand;
	/** `M_ApexDecal`: masked road paint. */
	TObjectPtr<UMaterialInterface> Decal;
};

namespace ApexTrackMaterials
{
	inline const TCHAR* const Folder = TEXT("/Game/Materials/Track");
	inline const TCHAR* const BaseName = TEXT("M_ApexTrackBase");
	inline const TCHAR* const EmissiveName = TEXT("M_ApexEmissive");
	inline const TCHAR* const BrandName = TEXT("M_ApexBrand");
	inline const TCHAR* const DecalName = TEXT("M_ApexDecal");

	/** `/Game/Materials/Track/<Name>`. */
	APEXSIM_API FString PackageName(const TCHAR* Name);
	/** `/Game/Materials/Track/<Name>.<Name>`. */
	APEXSIM_API FString ObjectPath(const TCHAR* Name);
	/**
	 * Load whichever of the four exist. Nothing is created here; a missing
	 * parent is logged by the builder that needs it.
	 */
	APEXSIM_API FApexTrackParents LoadParents();
	/**
	 * Whether a base parent was baked with the ground texture graph (it
	 * exposes `TextureAmount`) rather than the noise-tile fallback.
	 */
	APEXSIM_API bool HasGroundTextures(const UMaterialInterface* Base);
}	 // namespace ApexTrackMaterials

/** Parameter overrides for one material instance. */
struct FApexMaterialParams
{
	TArray<TPair<FName, float>> Scalars;
	TArray<TPair<FName, FLinearColor>> Vectors;
	TArray<TPair<FName, UTexture*>> Textures;

	void Scalar(const TCHAR* Name, float Value) { Scalars.Emplace(FName(Name), Value); }
	void Vector(const TCHAR* Name, const FLinearColor& Value) { Vectors.Emplace(FName(Name), Value); }
	void Texture(const TCHAR* Name, UTexture* Value) { Textures.Emplace(FName(Name), Value); }
	float FindScalar(const TCHAR* Name, float Default) const;
};

/**
 * How a track's generated assets come to exist, which is all that differs
 * between a cooked level and a runtime track: the editor saves material
 * instance constants and fully built meshes into packages, the game makes
 * dynamic instances and fast-built transient meshes and cooks their
 * collision itself.
 */
class IApexTrackAssetFactory
{
public:
	virtual ~IApexTrackAssetFactory() = default;

	/** An instance of `Parent` for material key `Key`, named `MI_<Key>`, with `Params` applied. */
	virtual UMaterialInterface* MakeMaterial(
		const FString& Key, UMaterialInterface* Parent, const FApexMaterialParams& Params) = 0;

	/**
	 * `SM_<Name>` from a filled description whose polygon groups are the
	 * slots, in order. `bTrackSurface` is a baked piece of the circuit (it
	 * wants collision against its own triangles) rather than a generated
	 * prop stand-in; `Bounds` is what the vertices span.
	 */
	virtual UStaticMesh* MakeMesh(const FString& Name, FMeshDescription& Description, const TArray<FName>& SlotNames,
		const TArray<UMaterialInterface*>& SlotMaterials, bool bTrackSurface, const FBox& Bounds) = 0;

	/**
	 * Whether the builder gives each track surface its own collision
	 * component: the runtime's meshes have none, since a mesh built in a
	 * cooked game cannot cook its own.
	 */
	virtual bool WantsCollisionComponents() const = 0;

	/** A name for the editor's outliner; nothing at runtime. */
	virtual void LabelActor(AActor* Actor, const FString& Label) {}
};

/** One mesh description ready to be built, prepared off the game thread. */
struct FApexPreparedMesh
{
	/** `SM_<Name>`: the scene mesh's name, or `Prop_<kind>` for a stand-in. */
	FString Name;
	/** Material keys, in slot (= polygon group) order. */
	TArray<FName> Slots;
	FMeshDescription Description;
	FBox Bounds = FBox(ForceInit);
	/** Index into `FApexTrackScene::Meshes`, or INDEX_NONE for a generated prop mesh. */
	int32 SceneMesh = INDEX_NONE;
	/** For a generated prop mesh: the kind it stands in for (`tree`, `start_gantry`, ...). */
	FString PropKind;
};

/** Every mesh of a track, as data, plus where the build has got to. */
struct FApexTrackGeometry
{
	TArray<TUniquePtr<FApexPreparedMesh>> Meshes;
	/** The next entry `BuildMeshes` turns into a UStaticMesh. */
	int32 NextToBuild = 0;
	/** Run-off band vertices and how many of them carry the seam fringe, for the log. */
	int32 BandVertices = 0;
	int32 FringeVertices = 0;

	bool IsBuilt() const { return NextToBuild >= Meshes.Num(); }
};

/**
 * Turns a parsed track export into a track in a world.
 *
 * One code path for both ways a circuit reaches the game, so they cannot
 * drift: the editor's `ApexTrackImport` runs it with a factory that saves
 * packages and then saves the world as `L_<Stem>`; `UApexTrackInstance`
 * runs it with a transient factory straight into the game world, spread
 * over several frames. The actors, tags and parameters are the same.
 *
 *  - `PrepareGeometry` is pure data and may run on any thread.
 *  - The rest runs on the game thread, in order: `BuildMaterials`,
 *    `BuildMeshes` (repeatedly, until it says it is done), `SpawnActors`.
 */
class APEXSIM_API FApexTrackSceneBuilder
{
public:
	/** Actor tag on every prop: the racing line and cameras skip them. */
	static const FName PropTag;
	/** Actor and component tag on every baked track surface: the road the racing line sits on. */
	static const FName TrackMeshTag;
	/** Actor tag on the start-light gantry, and component tag on each of its lenses. */
	static const FName StartLightsTag;
	static const FName StartLightTag;

	FApexTrackSceneBuilder(IApexTrackAssetFactory& InFactory, const FApexTrackParents& InParents);

	/** Mesh descriptions for every scene mesh and the generated stand-ins. Thread-safe. */
	static void PrepareGeometry(const FApexTrackScene& Scene, FApexTrackGeometry& Out);

	/** One material per key the scene uses, plus the stand-ins' own. */
	bool BuildMaterials(const FApexTrackScene& Scene, FString& OutError);

	/**
	 * Build meshes in order until `DeadlineSeconds` (`FPlatformTime::Seconds`)
	 * passes; at least one per call. Returns false on failure; the geometry
	 * says when everything is built.
	 */
	bool BuildMeshes(FApexTrackGeometry& Geometry, double DeadlineSeconds, FString& OutError);

	/** Reject meshes Unreal built badly, e.g. with NaN or empty bounds. */
	bool ValidateMeshes(FString& OutError) const;

	/**
	 * Spawn the track into `Level` of `World`: a static mesh actor per baked
	 * mesh, the props, the start lights, the fog and the post-process
	 * volume. Every actor spawned is appended to `OutActors`.
	 */
	void SpawnActors(const FApexTrackScene& Scene, UWorld* World, ULevel* Level, TArray<AActor*>& OutActors);

	/** For an owner that keeps a builder alive across garbage collections. */
	void AddReferencedObjects(FReferenceCollector& Collector);

	/** Material key -> generated instance. */
	const TMap<FString, TObjectPtr<UMaterialInterface>>& GetMaterials() const { return Materials; }

	/** Scene mesh name -> generated static mesh. */
	int32 NumBuiltMeshes() const { return Meshes.Num() + PropMeshes.Num(); }

	/**
	 * The road family's instances and the values their wet-road parameters
	 * were built with, so a reused runtime track can be dried out again.
	 */
	struct FRoadMaterial
	{
		FString Key;
		float Roughness = 0.0f;
		float RoughnessNoise = 0.0f;
	};
	const TArray<FRoadMaterial>& GetRoadMaterials() const { return RoadMaterials; }

private:
	/**
	 * What a prop resolves to. The authored kit first — `SM_<asset>` under
	 * the props root, then the kind's default asset — else the generated
	 * stand-in for the prop's own kind, else nothing (the placeholder cube).
	 */
	struct FResolvedProp
	{
		FString Kind;
		FString Asset;
		FString Text;
		TObjectPtr<UStaticMesh> Mesh;
		bool bAuthored = false;
		bool bFaceRoad = false;
		/** Yawed to look back up the course instead (a distance board). */
		bool bFaceUpCourse = false;
		bool bInstanced = false;
	};
	FResolvedProp ResolveProp(const FApexTrackProp& Prop);
	/** `SM_<asset>` of the authored kit, or null; cached either way. */
	UStaticMesh* FindAuthoredMesh(const FString& Kind, const FString& Asset);
	/** An instance of `M_ApexBrand` showing the texture at `TexturePath`, made once per key. */
	UMaterialInterface* TextureMaterialFor(const FString& Key, const FString& TexturePath);
	/** A lit instance of `M_ApexEmissive` for one of the kit's lamp/screen slots. */
	UMaterialInterface* EmissiveMaterialFor(FName Slot);
	/**
	 * An instance of `M_ApexDecal` showing the imported texture a decal key
	 * (`decal_<set>_<name>`) names; null when that texture is not imported,
	 * in which case the decal's meshes are left out.
	 */
	UMaterialInterface* DecalMaterialFor(const FString& Key);
	/** Brand, marker and emissive slot overrides for an authored mesh on a component. */
	void ApplyAuthoredSlots(UStaticMeshComponent* Component, const UStaticMesh* Mesh, const FString& Text);
	/** A stand laid out of bays and end caps under one actor. */
	AActor* SpawnGrandstand(UWorld* World, ULevel* Level, const FApexTrackProp& Prop, const FResolvedProp& Resolved,
		float YawDeg, int32 Index);
	/** The `StartLights` actor the race director drives during the countdown. */
	AActor* SpawnStartLights(const FApexTrackScene& Scene, UWorld* World, ULevel* Level);

	IApexTrackAssetFactory& Factory;
	FApexTrackParents Parents;
	bool bGroundTextures = false;
	FString PropsRoot;
	/** The scene's season and spectators, for the variant picks. */
	FApexTrackDressing Dressing;

	TMap<FString, TObjectPtr<UMaterialInterface>> Materials;
	/** Scene mesh name -> generated static mesh. */
	TMap<FString, TObjectPtr<UStaticMesh>> Meshes;
	/** Prop kind -> generated stand-in mesh (ground pivot, metres at scale 1). */
	TMap<FString, TObjectPtr<UStaticMesh>> PropMeshes;
	/** Object path -> authored mesh, null for the ones that are not imported. */
	TMap<FString, TObjectPtr<UStaticMesh>> AuthoredMeshes;
	/** Key -> brand/marker/emissive slot override; a null entry means "tried, no texture". */
	TMap<FString, TObjectPtr<UMaterialInterface>> SlotMaterials;
	/** Decal keys whose texture is not imported: their meshes are skipped. */
	TSet<FString> MissingDecals;
	/** Texts with no brand or marker texture, logged once each. */
	TSet<FString> UnknownTexts;
	TArray<FRoadMaterial> RoadMaterials;
	TObjectPtr<UStaticMesh> PlaceholderMesh;
};
