#!/usr/bin/env python3
"""
Bake the tiling ground textures the Unreal track materials sample.

    python scripts/bake_ground_textures.py               # every set
    python scripts/bake_ground_textures.py asphalt grass # a few
    python scripts/bake_ground_textures.py --size 512    # a quick look

Writes content/textures/ground/<set>_{col,nrm,rough}.png, which
`-run=ApexGroundTexImport` brings in as /Game/Ground/T_ground_<set>_*.

The generators live in content/props/_tools/apex_tex.py beside the prop
kit's, because they are the same numpy — fbm noise, a height field and a
normal taken from it — and a surface authored twice drifts. That module is
normally imported inside Blender; the import of `bpy` is optional there so
this script can run the generator half under plain CPython, which is the
whole reason the ground set is baked from the command line rather than from
a .blend.

Output is deterministic: every generator is seeded, so a rebuild produces
byte-identical files and the textures are gitignored rather than committed
(21 megapixel-scale PNGs of noise compress to tens of megabytes and would
be regenerated by anyone who touched a generator anyway).

Each map is tileable over apex_tex.GROUND_TILE_M of world in both
directions; `ApexGround::TextureTileM` on the Unreal side has to match.
"""

import argparse
import sys
from pathlib import Path

import numpy as np
from PIL import Image

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "content" / "props" / "_tools"))

import apex_tex  # noqa: E402

OUT_DIR = REPO_ROOT / "content" / "textures" / "ground"


def _write(path, array, mode):
    """A float array in 0..1 as an 8-bit PNG.

    Row 0 of the array is written as row 0 of the image, which is the
    convention `normal_from_height` already assumes: its `dy` runs down the
    rows and Unreal's V runs down the image, so the green channel comes out
    the way a tangent-space sampler expects without a flip anywhere.
    """
    data = np.clip(np.asarray(array), 0.0, 1.0)
    png = Image.fromarray(np.round(data * 255.0).astype(np.uint8), mode)
    path.parent.mkdir(parents=True, exist_ok=True)
    png.save(path, optimize=True)
    return path


def bake(name, size):
    """One set: colour, normal and roughness, returned as written paths."""
    previous = apex_tex.GROUND_SIZE
    apex_tex.GROUND_SIZE = size
    try:
        color, rough, height, strength = apex_tex.GROUND_SLOTS[name]()
    finally:
        apex_tex.GROUND_SIZE = previous
    written = [
        _write(OUT_DIR / f"{name}_col.png", color, "RGB"),
        _write(OUT_DIR / f"{name}_nrm.png",
               apex_tex.normal_from_height(height, strength), "RGB"),
        # Greyscale: the importer brings it in as a mask texture and only
        # ever reads red, so three identical channels would be three times
        # the file for nothing.
        _write(OUT_DIR / f"{name}_rough.png", rough, "L"),
    ]
    mean = np.asarray(color).reshape(-1, 3).mean(axis=0)
    print(f"  {name:10s} {size}^2  colour mean {mean[0]:.3f} {mean[1]:.3f} {mean[2]:.3f}")
    return written


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("sets", nargs="*", help="set names; default every one")
    parser.add_argument("--size", type=int, default=apex_tex.GROUND_SIZE,
                        help="pixels per side (default %(default)s)")
    parser.add_argument("--list", action="store_true", help="list the sets and stop")
    args = parser.parse_args(argv)

    if args.list:
        for name in sorted(apex_tex.GROUND_SLOTS):
            print(name)
        return 0

    names = args.sets or sorted(apex_tex.GROUND_SLOTS)
    unknown = [n for n in names if n not in apex_tex.GROUND_SLOTS]
    if unknown:
        parser.error(f"unknown set(s): {', '.join(unknown)}")

    print(f"baking {len(names)} ground texture set(s) into {OUT_DIR}")
    count = 0
    for name in names:
        count += len(bake(name, args.size))
    print(f"wrote {count} file(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
