#pragma once

#include "CoreMinimal.h"
#include "UObject/ObjectPtr.h"

class UMaterialInterface;
struct FApexGlbMaterial;

/**
 * The parent materials a runtime car's slots are instances of. Cooked
 * assets under `/Game/Materials/Car`, generated by the editor's
 * `ApexMaterialBake` beside the track parents, and the only car content that
 * is cooked: every car, wheel and DRS flap is built from its GLB at runtime
 * (`UApexCarContentSubsystem`).
 *
 * All four are two-sided (every car GLB's material is `doubleSided`) and
 * take the parameter names Interchange's glTF parents used, which is what
 * the livery, ghost and brake-light code sets:
 *
 *  - `BaseColorFactor` (linear RGBA), times `BaseColorTexture` (sRGB, white by default);
 *  - `MetallicFactor`, `RoughnessFactor`;
 *  - `EmissiveFactor` (linear RGB). `KHR_materials_emissive_strength` is
 *    not drawn: Interchange's parent ignored it too, and the brake and tail
 *    lights scale this colour themselves;
 *  - `AlphaCutoff` on the masked parent, `ClearCoatFactor` and
 *    `ClearCoatRoughnessFactor` on the clear-coat one.
 */
struct FApexCarParents
{
	/** `M_ApexCarOpaque`. */
	TObjectPtr<UMaterialInterface> Opaque;
	/** `M_ApexCarClearCoat`: an opaque material with `KHR_materials_clearcoat` (the paint). */
	TObjectPtr<UMaterialInterface> ClearCoat;
	/** `M_ApexCarMasked`: `alphaMode` MASK (logos). */
	TObjectPtr<UMaterialInterface> Masked;
	/** `M_ApexCarTranslucent`: `alphaMode` BLEND (glass). */
	TObjectPtr<UMaterialInterface> Translucent;

	/** The parent a glTF material wants; falls back to `Opaque`, which may be null. */
	UMaterialInterface* For(const FApexGlbMaterial& Material) const;
	bool IsComplete() const { return Opaque && ClearCoat && Masked && Translucent; }
};

namespace ApexCarMaterials
{
	inline const TCHAR* const Folder = TEXT("/Game/Materials/Car");
	inline const TCHAR* const OpaqueName = TEXT("M_ApexCarOpaque");
	inline const TCHAR* const ClearCoatName = TEXT("M_ApexCarClearCoat");
	inline const TCHAR* const MaskedName = TEXT("M_ApexCarMasked");
	inline const TCHAR* const TranslucentName = TEXT("M_ApexCarTranslucent");

	/** The parameter names, shared by the bake and the runtime. */
	inline const TCHAR* const BaseColorFactor = TEXT("BaseColorFactor");
	inline const TCHAR* const BaseColorTexture = TEXT("BaseColorTexture");
	inline const TCHAR* const MetallicFactor = TEXT("MetallicFactor");
	inline const TCHAR* const RoughnessFactor = TEXT("RoughnessFactor");
	inline const TCHAR* const EmissiveFactor = TEXT("EmissiveFactor");
	inline const TCHAR* const AlphaCutoff = TEXT("AlphaCutoff");
	inline const TCHAR* const ClearCoatFactor = TEXT("ClearCoatFactor");
	inline const TCHAR* const ClearCoatRoughnessFactor = TEXT("ClearCoatRoughnessFactor");

	/** `/Game/Materials/Car/<Name>`. */
	APEXSIM_API FString PackageName(const TCHAR* Name);
	/** `/Game/Materials/Car/<Name>.<Name>`. */
	APEXSIM_API FString ObjectPath(const TCHAR* Name);
	/** Load whichever of the four exist; nothing is created here. */
	APEXSIM_API FApexCarParents LoadParents();
}
