#pragma once

#include "CoreMinimal.h"
#include "UObject/ObjectPtr.h"

class UMaterialInterface;
struct FApexGlbMaterial;

/**
 * The parent materials a runtime car's slots are instances of. Cooked
 * assets under `/Game/Materials/Car`, generated by the editor's
 * `ApexMaterialBake` beside the track parents, and the only car content that
 * is cooked: every car, wheel and DRS flap is built from its GLB at runtime
 * (`UApexCarContentSubsystem`).
 *
 * All four are two-sided (every car GLB's material is `doubleSided`) and
 * take the parameter names Interchange's glTF parents used, which is what
 * the livery, ghost and brake-light code sets:
 *
 *  - `BaseColorFactor` (linear RGBA), times `BaseColorTexture` (sRGB, white by default);
 *  - `MetallicFactor`, `RoughnessFactor`;
 *  - `EmissiveFactor` (linear RGB). `KHR_materials_emissive_strength` is
 *    not drawn: Interchange's parent ignored it too, and the brake and tail
 *    lights scale this colour themselves;
 *  - `AlphaCutoff` on the masked parent, `ClearCoatFactor` and
 *    `ClearCoatRoughnessFactor` on the clear-coat one.
 */
struct FApexCarParents
{
	/** `M_ApexCarOpaque`. */
	TObjectPtr<UMaterialInterface> Opaque;
	/** `M_ApexCarClearCoat`: an opaque material with `KHR_materials_clearcoat` (the paint). */
	TObjectPtr<UMaterialInterface> ClearCoat;
	/** `M_ApexCarMasked`: `alphaMode` MASK (logos). */
	TObjectPtr<UMaterialInterface> Masked;
	/** `M_ApexCarTranslucent`: `alphaMode` BLEND (glass). */
	TObjectPtr<UMaterialInterface> Translucent;
	/**
	 * `M_ApexCarTyre`: the `wheel_tyre` slot's (ApexCarMaterials::TyreCpd).
	 * Optional: a project baked before it draws its tyres with `Opaque`.
	 */
	TObjectPtr<UMaterialInterface> Tyre;

	/**
	 * The parent a glTF material wants (`Tyre` for an opaque `wheel_tyre`
	 * when it is baked); falls back to `Opaque`, which may be null.
	 */
	UMaterialInterface* For(const FApexGlbMaterial& Material) const;
	bool IsComplete() const { return Opaque && ClearCoat && Masked && Translucent; }
};

namespace ApexCarMaterials
{
	inline const TCHAR* const Folder = TEXT("/Game/Materials/Car");
	inline const TCHAR* const OpaqueName = TEXT("M_ApexCarOpaque");
	inline const TCHAR* const ClearCoatName = TEXT("M_ApexCarClearCoat");
	inline const TCHAR* const MaskedName = TEXT("M_ApexCarMasked");
	inline const TCHAR* const TranslucentName = TEXT("M_ApexCarTranslucent");
	inline const TCHAR* const TyreName = TEXT("M_ApexCarTyre");
	/** The glTF material (slot) the tyre parent is for (docs/content/cars.md, Wheels). */
	inline const TCHAR* const TyreSlotName = TEXT("wheel_tyre");
	/**
	 * The tyre parent's sidewall ring height, a share of the radius. Also
	 * how the bake tells a tyre parent from before the ring.
	 */
	inline const TCHAR* const TyreBandWidth = TEXT("TyreBandWidth");

	/** The parameter names, shared by the bake and the runtime. */
	inline const TCHAR* const BaseColorFactor = TEXT("BaseColorFactor");
	inline const TCHAR* const BaseColorTexture = TEXT("BaseColorTexture");
	inline const TCHAR* const MetallicFactor = TEXT("MetallicFactor");
	inline const TCHAR* const RoughnessFactor = TEXT("RoughnessFactor");
	inline const TCHAR* const EmissiveFactor = TEXT("EmissiveFactor");
	inline const TCHAR* const AlphaCutoff = TEXT("AlphaCutoff");
	inline const TCHAR* const ClearCoatFactor = TEXT("ClearCoatFactor");
	inline const TCHAR* const ClearCoatRoughnessFactor = TEXT("ClearCoatRoughnessFactor");

	/**
	 * The damage graph every car parent carries (ApexCarDamage.h has the
	 * custom primitive data it reads): the dent depth and crumple at a
	 * zone's full visual amount, cm. `DamageDentCm` is also how the bake
	 * tells a parent from before the graph.
	 */
	inline const TCHAR* const DamageDentCm = TEXT("DamageDentCm");
	inline const TCHAR* const DamageCrumpleCm = TEXT("DamageCrumpleCm");

	/**
	 * `M_ApexCarSmoke`: the lit translucent parent the smoke, steam and
	 * sparks are drawn with (AApexCarEffectsActor), on instanced meshes;
	 * per-instance data 0 opacity, 1 shade (black to white), 2 glow (an
	 * emissive multiplier), 3 edge softness (1 for a puff, 0 for a spark).
	 */
	inline const TCHAR* const SmokeName = TEXT("M_ApexCarSmoke");
	inline constexpr int32 SmokeCustomFloats = 4;

	/**
	 * `M_ApexCarTyre` draws the tyre from the wheel component's custom
	 * primitive data, so one instance serves every car on that wheel and
	 * each tyre still shows its own state (FApexCarWheelSet writes it). The
	 * class tyres carry no UVs, so the tread is laid from the mesh's own
	 * position: the axle on X, `theta` round it from +Y toward +Z. Starts at
	 * 16, past the damage graph's (ApexDamage::CpdCount), which the rims'
	 * opaque parent reads from the same component.
	 */
	namespace TyreCpd
	{
		/** The tyre's radius and half width in the mesh's own units. */
		inline constexpr int32 RadiusLocal = 16;
		inline constexpr int32 HalfWidthLocal = 17;
		/** The same as drawn, world cm. */
		inline constexpr int32 RadiusCm = 18;
		inline constexpr int32 HalfWidthCm = 19;
		/** 0 slick, 1 intermediate, 2 wet (ApexWheels::TreadIndex). */
		inline constexpr int32 Tread = 20;
		/** +1 or -1: which way `theta` rolls forward, so a directional tread points the same way on both sides. */
		inline constexpr int32 Chevron = 21;
		/** 0..1 each. */
		inline constexpr int32 Wear = 22;
		inline constexpr int32 Wetness = 23;
		inline constexpr int32 FlatSpot = 24;
		/** Where the flat spot is, `theta` radians. */
		inline constexpr int32 FlatSpotAngle = 25;
		/** How far a deflated tyre squats, world cm. */
		inline constexpr int32 SagCm = 26;
		/** The compound's ring on the sidewalls, linear RGB (27..29, 30 unused); black for none. */
		inline constexpr int32 BandColour = 27;
		inline constexpr int32 Count = 31;
	}

	/** `/Game/Materials/Car/<Name>`. */
	APEXSIM_API FString PackageName(const TCHAR* Name);
	/** `/Game/Materials/Car/<Name>.<Name>`. */
	APEXSIM_API FString ObjectPath(const TCHAR* Name);
	/** Load whichever of the four exist; nothing is created here. */
	APEXSIM_API FApexCarParents LoadParents();
}
